### ISSUE TITLE
Convolution: Ability to update weights and biases

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#162]
### Feature description

Support updating weight and bias in convolution (1D and 2D).

### Feature motivation

Currently weights and biases attributes are initialized with random data. There are no public methods to override them. 

### (Optional) Suggest a Solution

Create public methods to override the weight and bias attributes. Even better option would be to provide with additional constructors that can take the weights and biases. This is highly useful for inferencing mode. Currently the model assumes the use case for training.

**Comment by nathanielsimard** [comment]
At the moment, there is a way to load weights into every module, although it is not well-documented. Each module can load any state, much like `load_state_dict` in PyTorch.

```rust
let config = MyConfig::new(); // Can also load from disk
let mut module = MyModule::new(&config);
let state = module.state(); // Can also load from disk
module.load(state);
```

You can manually build the state, but I would suggest saving the state of your model to a file (e.g., json.gz) and editing it using the trained weights.

Another possible solution would be to make the parameters of the model pub, so that you can update them like this:

```rust
let mut conv = Conv...;
conv.weights.update(...);
```

However, it's tedious to load all the weights of every module in a model that way, and I think the state API is better suited for that purpose. If the goal is really to update the weights programmatically for only convolution, making the field pub can be a viable option.

**Comment by antimora** [comment]
I have started using burn-rs in my project. For example, I am using `conv` for downsampling spectrogram and some other tensor operators for unit testing. So it helps if individual components, such as `conv`, are standalone. 

The next big usage of burn-rs for me is inference using my own trained weights. So it would be very helpful if I can build the graph myself. I believe this is a killer feature by burn-rs. I would like to contribute in this area more. 

Ultimately it would be great if I could train my models with burn-rs. I am currently using PyTorch, like many.

**Comment by nathanielsimard** [comment]
I'm not sure what you mean by standalone, but you can only use `burn-tensor` as dependency if you want and call the `conv2` function using your own tensors without the `Module` API.

**Comment by antimora** [comment]
@nathanielsimard I think your recent work with #210 solves this. What do you think? I filed this ticket and the main think I wanted is to pass weights and biases when initializing Conv. So my ask is solved. However, if you think there is further about it, please comment, otherwise please close as complete.
