### ISSUE TITLE
Proposal: Serialize/Deserialize module directly instead of loading into `State` first

### ISSUE THREAD

**Issue by antimora** [burn-rs/burn#234]
### Feature description
Remove the intermediate `State` (de)serialization when module's state is save and loaded.

### Feature motivation

The main motivation is make the load/saving state more efficient. For models with size of 500MB or larger, the loading to a state object eats up memory and CPU cycles.

### (Optional) Suggest a Solution

Create a serde serializer/deserializer for module. The module already supports tree visitor pattern. This solution also can capture the graph information, such node types, edges. This can even be used by ONNX exporter (#204).

### Considerations

This proposal does not take into account the original reason why State struct was created in the first place. The author of this proposal assumes it was easier/quicker to use native types to serialize because State's attributes are serde serializable natively.

**Comment by nathanielsimard** [comment]
I was thinking about it, and it would be possible to serialize a module directly, but not necessary deserialize it. Why? Because modules consist not only of parameters, but also of other types that may not implement serde.

This is important because some modules may require shared parameters that you don't want to serialize twice, and a constructor function is needed to receive them. In other cases, you may want to enhance a model with a database connection to retrieve embeddings that serve as memory while still implementing the same trait. However, this requires the database connection to be owned by the module, and it doesn't make sense to serialize a database connection. It may even pose a security risk.

It's probably a similar reason why PyTorch has `state_dict` to save parameters.

**Comment by antimora** [comment]
@nathanielsimard

> I was thinking about it, and it would be possible to serialize a module directly, but not necessary deserialize it. Why? Because modules consist not only of parameters, but also of other types that may not implement serde.

I'd like to clarify my position. I don't intend to use the standard (de)serializer, as I understand that some parts of a module may not be de/serializable. That's why, to my understanding, we have the State object: 1) everything included in the State must be de/serializable (meaning we selectively choose what to include), and 2) State is readily serializable with serde.

My question is, why do we need to maintain the intermediate State before serializing/deserializing? Are there any other reasons besides those I mentioned above? Currently, the process is: file -> State -> module -> State -> file. Can we instead use: file -> module -> file? The primary benefit I see is no memory doubling, which is useful when dealing with large models like the 1GB model [referenced here](https://github.com/openai/whisper/blob/main/model-card.md). Additionally, I believe it would offer a more flexible design if we need to (de)serialize custom elements like symbolic links to database or file objects, as in your example.

The solution could involve implementing a custom [serde (de)serialization](https://serde.rs/custom-serialization.html) by pulling the current logic.

Let me know what you think.

**Comment by nathanielsimard** [comment]
Hi, you are right about the use of the State: to chose what is (de)serializable, but I think the struct should not contain the data, as it occupies to much memory. The solution won't be file -> module -> file, but probably the same in performance to allow streaming everything to file.

**Comment by antimora** [comment]
OK. Looking forward to seeing your solution.

**Comment by jmacglashan** [comment]
Avoiding intermediate duplicates certainly seems like a reasonable goal. Personally, I would love to have vanilla serde support, as we've discussed in the other thread. I think that makes it more simple to build custom code since serde is so ubiquitous in Rust. However, if there are reasons that won't pan out in Burn's design, it might be nice to support it whenever possible and then have more general escape hatches for the special cases that use more indirect methods (and which are available even on the modules that can support vanilla serde). I suspect the times it would be possible to have vanilla serde would be the overwhelming majority of neural net layers at least.

If there is an intermediate step representation it does seem a little tricky to avoid duplicates on the deserialization. I'm not super up to speed on the current module serialization, but I suspect that could be minimized if you have `from_state` on the special module implementation that takes ownership of the state and all remaining non-serialized values.

As an illustration of that idea (using bincode purely as an example codec):
```rust
let module_state: State<B> = bincode::deserialize_from(File::Open("path/to/module/state/file").unwrap());
let module = MyModule::from_state(
    module_state, 
    // other non-state args here
);
```
Since the `from_state` takes owership, I think that might allow you to avoid the memory duplication when constructing the actual module.

**Comment by nathanielsimard** [comment]
I'm closing this, since we now have the `Record` trait which serves that goal.
