### ISSUE TITLE
Standard Distribution not sampling negative numbers on ndarray and wgpu backends

### ISSUE THREAD

**Issue by vultix** [burn-rs/burn#468]
**Describe the bug**
Tensors created using the ndarray or wgpu backends using `Distribution::Standard` only contain positive elements.  The tch backend correctly samples both positive and negative values.

**To Reproduce**
Run this script:
```rust
use burn::tensor::{Distribution, Tensor};
use burn_ndarray::NdArrayBackend;
use burn_tch::TchBackend;

fn main() {
    let torch: Tensor<TchBackend<f32>, 1> = Tensor::random([20], Distribution::Standard);
    let ndarray: Tensor<NdArrayBackend<f32>, 1> = Tensor::random([20], Distribution::Standard);

    println!("Torch: {torch}");
    println!("NdArray: {ndarray}");
}
```

**Expected behavior**
The ndarray tensor should contain both positive and negative values, similar to the tch backend.

**Comment by antimora** [comment]
Thank you. We will look into this.

**Comment by antimora** [comment]
@vultix OK. I have investigated the issue and I confirm there is a bug. However, the bug is in TchBackend's implementation. It was returning the normal distribution instead of uniform distribution performed by [torch's rand function](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand). If you need normal distribution, please use Distribution::Uniform(0.0, 1.0), which is equivalent to what you were expecting. 

The bug has been fixed by this PR: https://github.com/burn-rs/burn/pull/469

I updated the documentation to make it clear.

**Comment by vultix** [comment]
@antimora I'm a bit confused by this.  My understanding is that `Distribution::Standard` means the standard normal distribution and behaves as a shorthand for `Distribution::Normal(0.0, 1.0)`.  This is consistent with a quick google search of "standard distribution" 
![image](https://github.com/burn-rs/burn/assets/5114062/70c1086b-3343-43af-b2a6-76255b196d6e)

If the intent is for `Distribution::Standard` to be shorthand for `Distribution::Uniform(0.0, 1.0)`, then I'd propose an alternative, less confusing name.  Perhaps we could have two variants, `Distribution::StandardNormal` and `Distribution::StandardUniform`?

**Comment by antimora** [comment]
> @antimora I'm a bit confused by this. My understanding is that `Distribution::Standard` means the standard normal distribution and behaves as a shorthand for `Distribution::Normal(0.0, 1.0)`. This is consistent with a quick google search of "standard distribution" ![image](https://user-images.githubusercontent.com/5114062/251292994-70c1086b-3343-43af-b2a6-76255b196d6e.png)
> 
> If the intent is for `Distribution::Standard` to be shorthand for `Distribution::Uniform(0.0, 1.0)`, then I'd propose an alternative, less confusing name. Perhaps we could have two variants, `Distribution::StandardNormal` and `Distribution::StandardUniform`?

Borrowed the naming from rand crate. Here a [direct link to the standard variant.](https://rust-random.github.io/rand/rand/distributions/index.html#the-standard-distribution).

Not the best name, I agree and probably `Distribution::Default` would be better name though. 

Should we rename `Distribution::Standard` to `Distribution::Default`, @nathanielsimard ? What do you think? It might be worth considering since not many people use it yet and it might confuse or introduce more bugs over time even more.

**Comment by nathanielsimard** [comment]
Yeah even I got confused, since I implemented the standard variant using `Normal(0, 1)` with the tch backend. I think we should rename the `Distribution::Standard` to `Distribution::StandardNormal` and implement `Default` for `Distribution` which returns `Uniform(0, 1)`.

**Comment by antimora** [comment]
@nathanielsimard 
> Yeah even I got confused, since I implemented the standard variant using `Normal(0, 1)` with the tch backend. I think we should rename the `Distribution::Standard` to `Distribution::StandardNormal` and implement `Default` for `Distribution` which returns `Uniform(0, 1)`.

I will rename `Distribution::Standard` to `Distribution::Default` not `Distribution::StandardNormal` because it's not standard normal.  `Distribution::Standard` in the current form generates like `Uniform(0, 1)` not exact the same, please refer to https://rust-random.github.io/rand/rand/distributions/index.html#uniform-numeric-ranges and https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand. The key difference is the type definition. `Uniform(0, 1)` will not work for float or bools.

**Comment by antimora** [comment]
Done in the PR

**Comment by antimora** [comment]
> Yeah even I got confused, since I implemented the standard variant using `Normal(0, 1)` with the tch backend. I think we should rename the `Distribution::Standard` to `Distribution::StandardNormal` and implement `Default` for `Distribution` which returns `Uniform(0, 1)`.

I'm planning to change the name of `Distribution::Standard` to `Distribution::Default`, rather than `Distribution::StandardNormal`, mainly because it doesn't generate standard normal distributions. In its current form, `Distribution::Standard` behaves more like `Uniform(0, 1)`, although not exactly the same. You can check out the detailed behavior at these links: [Rust Rand Library](https://rust-random.github.io/rand/rand/distributions/index.html#uniform-numeric-ranges) and [PyTorch Documentation](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand).

It's important to highlight that the key difference lies in the type definition. For instance, `Uniform(0, 1)` won't be suitable for float or boolean types. So keep that in mind!
