### ISSUE TITLE
Llama2 Slow Loading in burn

### ISSUE THREAD

**Issue by Gadersd** [burn-rs/burn#554]
After I ported Llama2 to burn (https://github.com/Gadersd/llama2-burn) I tested it on llama2-7b-chat. I used `DefaultRecorder` to save the burn model which took at least 30 minutes, possibly much longer. I noticed that the CPU model loading was significantly slower in burn than in pytorch, ~8 mins vs ~ 1 min. Might the loading speed discrepancy be due to burn's model format .mpk.gz?

**Comment by antimora** [comment]
Interesting. @nathanielsimard and I worked in this area, so definitely interested to know what's going on. Have you tried saving in bincode? It's less portable but it's fast. Also if there is an option not to compress, try it if it helps. At this point, I am trying to poke around to understand. Obviously you're one of the first to deal with large weights.

**Comment by nathanielsimard** [comment]
There are multiple potential reasons for slow loading. First, make sure you are using --release since the gzip compression/decompression relies on https://github.com/rust-lang/flate2-rs and serde. You can choose a different recorder (save format) to test out, such as DefaultRecorder which saves weights using f32 and message pack format with gzip compression. As mentioned by @antimora, you can also use the SensitiveCompactRecorder to utilize the bin format with gzip compression. Of course, you can also try without gzip compression to see if this is the problem.

**Comment by Gadersd** [comment]
I checked and the issue isn't with compression or the type of recorder used. The issue is that burn currently doesn't use buffered IO since that isn't Rust's default. I just submitted a pull request resolving the issue.

**Comment by antimora** [comment]
@Gadersd, while we're discussing file formats, there are a couple of points you might find relavent :

1. The Bincode format (with a .bin extension) is highly efficient. However, it relies on position-based data retrieval for structs, which means any change in field order will disrupt data loading. On the other hand, the MessagePack (used by DefaultFileRecorder) operates with a named option, essentially utilizing field names. I mention this because I noticed that for stable fusion, you've employed the .bin extension, which I assume is using Bincode. Bincode is particularly apt for files accompanying model data, similar to our MNIST Web example in WASM.
2. You might want to explore PrecisionSettings. It allows data to be saved in f16 format but read back as either f32 or f16. If you haven't yet, it's worth leveraging this feature. We introduced it in our latest release, thanks to the diligent efforts of @nathanielsimard. =)
