### ISSUE TITLE
Windows: Downloading Python dependencies Error

### ISSUE THREAD

**Issue by mashirooooo** [burn-rs/burn#564]
**Describe the bug**
When running examples and downloading Python dependencies in the virtual environment (venv) on Windows, the directory structure of the venv is inconsistent with that on Unix systems. This discrepancy leads to download errors

**Comment by antimora** [comment]
Can you please what kind of errors and inconsistency do you see? It would be helpful to troubleshoot. Perhaps the paths were assumed.

**Comment by mashirooooo** [comment]
When using venv on Unix systems, the Python executable `python3` is located in the `.bin` directory, whereas on Windows, the Python executable `python.exe` is located in the `Scripts` directory；
If possible, could you please make the script `burn-dataset/src/source/huggingface/downloader.rs` compatible with Windows? Currently, I have continued the process by using `Revert "Install dataset downloader python deps in venv (#496)"` because I'm not familiar with Python, and thus, I am unable to submit a pull request.

**Comment by nathanielsimard** [comment]
Burn should be compatible with Windows, so we definitively need to fix it if there is a problem.

**Comment by Macil** [comment]
The MNIST example doesn't work on Windows (assuming ~/.cache/burn-dataset/mnist.db doesn't exist yet and needs to be downloaded) and fails with this output:

```
PS E:\chris\Coding\burn> cargo run --example mnist --release --features ndarray
    Finished release [optimized] target(s) in 0.74s
warning: the following packages contain code that will be rejected by a future version of Rust: nom v1.2.4
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target\release\examples\mnist.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', burn-dataset\src\source\huggingface\downloader.rs:237:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\examples\mnist.exe` (exit code: 101)
```

Changing the code to print the command before running it shows that it's trying to run ~/.cache/burn-dataset/venv/bin/python3, but there's no such executable. It works if it instead runs ~/.cache/burn-dataset/venv/Scripts/python. ([VirtualEnv arbitrarily uses the "Scripts" directory instead of "bin" on Windows.](https://stackoverflow.com/questions/43826134/why-is-the-bin-directory-named-differently-scripts-on-windows))
