### ISSUE TITLE
Performance WGPU: Managed Memory

### ISSUE THREAD

**Issue by nathanielsimard** [burn-rs/burn#582]
When creating buffers with `pub fn create_buffer(&self, size: usize) -> Arc<Buffer>`, we should try to reuse existing buffers that should be managed with a memory pool. This would reduce the amount of allocation and deallocation and increase performance while potentially reducing memory usage.

**Comment by DrChat** [comment]
Found this library from the `wgpu` folk that could help: https://github.com/gfx-rs/range-alloc

Some working notes:
In `burn_wgpu::context::base::Context::create_buffer_with_data_options`, it would be best to avoid calling `Device::create_buffer_init` or `Device::create_buffer` directly and instead maintain our own pool of memory buffers.
The return value should be altered so that instead of returning a `wgpu::Buffer`, it returns an `Arc`-like struct that either describes a range inside of a `wgpu::Buffer` or a `wgpu::Buffer` (if the allocation is large enough).

**Comment by nathanielsimard** [comment]
@DrChat Thanks for the suggestion. Once the system is in place, we should update `create_buffer_with_data_options` to reuse the pool. Also, I think there are potential problems with large buffers. Contrary to CUDA, I don't think we can allocate a very large buffer (as large as the physical memory), so it might reduce the kind of memory structure we could adopt. Though I'm unsure if the memory option is on shared storage buffers or buffers loaded into a kernel. Also, if we work with slice buffers, we should ensure that we can load them partially into a compute module, but maybe that is what `wgpu::BufferBinding` is for!

Creating our own buffer enum is interesting. I think it's probably a good refactor regardless of the implementation details!

**Comment by DrChat** [comment]
Alright, so I put a little WIP branch together that implements this functionality.
Instead of loading buffers directly onto the GPU, the code now loads them into main memory and then into the GPU as they are demanded by compute tasks.

This is either running very nicely or very poorly on my system, depends on if the results are correct :)
Before this refactor though, I had no chance of running the model I'm running now.

**Comment by nathanielsimard** [comment]
@DrChat you can submit a PR. Eventhough it is in WIP, we can better collaborate on this.

**Comment by DrChat** [comment]
Yeah totally fair - submitted #734.

**Comment by louisfd** [comment]
Closing as this was solved in #826
