### ISSUE TITLE
How to include tensors in a module?

### ISSUE THREAD

**Issue by wbrickner** [burn-rs/burn#605]
I am writing a custom loss function that precomputes a bunch of tensors (very expensive) and then can use them to cheaply compute loss later on.

- I can't store the tensors on my model (on which I impl `TrainStep` + `ValidStep`), as `Tensor` is not a `Module`, so `#[derive(Module)]` doesn't work.
- I can't store it in a global because `Tensor<B, ...>` has a generic for backend, and I can't pick 1 backend because my loss is generic over backend.
- I can't build the loss function on the fly inside the `step` function, as in the MNIST example, because this kills performance.
- I don't understand the meaning / behavior of the `Module` trait functions / associated types, so I can't implement it safely myself.

Can you explain how this can be done?
Thanks!

**Comment by antimora** [comment]
Just recently (a month ago) we merged all module implementation for Tensor. The code is in the main. Please see this PR: https://github.com/burn-rs/burn/pull/459

**Comment by antimora** [comment]
Here is the example that should work:

```rust
// Define the model structure
#[derive(Module, Debug)]
pub struct ClassificationModel<B: Backend> {
    transformer: TransformerEncoder<B>,
    embedding_pos: Embedding<B>,
    layer_norm: LayerNorm<B>,
    output: Linear<B>,
    n_classes: usize,
    max_seq_length: usize,
    sinusoids: Tensor<B, 2>, // <-- Tensor works now
}
```

**Comment by antimora** [comment]
Also just recently we implemented module for PhantomData in case you want to use Module<B> but without needing to reference B, so the following will work:

```rust
#[derive(Module, Debug)]
pub struct Model<B: Backend> {
    dropout: Dropout,
    n_classes: usize,
    max_seq_length: usize,
    phantom: PhantomData<B>, // <-- this works now
}
```

**Comment by wbrickner** [comment]
Just to be perfectly clear, the tensors *are not* modified by the optimizer, correct? they are immutable and only used for gradient computations?

**Comment by antimora** [comment]
> .set_require_grad(false)

Good question! I think the autodiff should abide the `require_grad` flag. You can probably double check if this flag is true when a new tensor created. You can disable it with `.set_require_grad(false)`

@nathanielsimard , can you please confirm this?

**Comment by nathanielsimard** [comment]
@wbrickner Both `Tensor<B, D>` and `Param<Tensor<B, D>>` implement the `Module` trait. The difference is that `Param<Tensor<B, D>>` is a parameter of the model, so the weights are included in the module record and are trainable by default.

`Tensor<B, D>` is considered a constant, so it's not included in the record nor is updated by the optimizer. Since its value can be computed when the module is initialized, we don't need to save it.

If you want the tensor to be included with the model record, but not updated by the optimizer, you can just call `set_require_grad(false)` when initializing the module.

Hope that's clear, we will document it more deeply in the book.
