### ISSUE TITLE
Ability to interrupt training loop

### ISSUE THREAD

**Issue by dae** [burn-rs/burn#714]
When integrating burn into a GUI app, it would be nice to give the user the ability to interrupt a long training process if they decide they don't want to wait for it to complete.

The way I thought this might be implemented is allowing the user to pass in a `should_stop: Arc<AtomicBool>` to LearnerBuilder, which would pass it on to the learner. The learner would pass it on to run(_multi_device), and at the end of each loop iteration, if the flag is set, it would terminate processing. To minimize API changes, I thought it might be best to return the partially-changed model, rather than have it return an error flag.

Some possible downsides: AtomicBool is not [universally available](https://doc.rust-lang.org/std/sync/atomic/#portability); there may be a minor performance hit.

Is this something you guys would be amenable to if I write up a PR? Do you have alternative thoughts on how it might be implemented?

**Comment by nathanielsimard** [comment]
Yes, we should give the ability to interrupt training! Using an atomic bool is probably quite easy to integrate. I'm also thinking of supporting early stopping and other algorithms that may affect the training duration. In that regard, I think we could implement a learner callback that shares the same atomic bool.

So, I don't think we should pass the atomic bool to the builder, but fetch the atomic bool from the builder, so that multiple callbacks/ways of interrupting share the same state.

Also, I would wrap the Atomic Bool into a struct with methods, so we could replace the atomic with something else depending on the platform.

```rust
#[derive(Clone)]
pub struct TrainingInterruption {
    state: Arc<AtomicBool>
}

impl TrainingInterruption {
    fn stop(&self) {
        self.state.store(false, Ordering::Relaxed);
    }
    
    fn should_stop(&self) -> bool {
        self.state.load(Ordering::Relaxed)
    }
}
```

We could also support multiple stopping behaviors, like stopping at the next epoch, stopping immediately, etc., using an AtomicUsize as a state that returns a proper enum when read.

**Comment by dae** [comment]
My first thought was to put this in the existing callback (eg allow a bool return value from on_train_item), but then I saw the callback uses a one way channel, so sending something back in the other direction seemed a bit more involved.

> but fetch the atomic bool from the builder,

Do you mean the builder should create one when it is created, and provide a method to return a cloned copy before the learner is built?

**Comment by nathanielsimard** [comment]
> My first thought was to put this in the existing callback (eg allow a bool return value from on_train_item), but then I saw the callback uses a one way channel, so sending something back in the other direction seemed a bit more involved.

Yeah I think a callback could be created, but with the `TrainingInterruption` state to manipulate.

> Do you mean the builder should create one when it is created, and provide a method to return a cloned copy before the learner is built?

Yes I think the builder should create a TrainingInterruption by default and make it available so other strcuts can be created with it. We could also provide a way to create your type with a closure:

```rust
builder.interrup(|interuption| GuiCancelation::new(interuption, gui_state))

let interruption = builder.interruption();
my_btn.on_click(|_| interruption.stop());
...
```

**Comment by Luni-4** [comment]
@dae 

Which GUI library are you using for your application?

**Comment by dae** [comment]
Qt, Android and iOS, though this will probably go in our shared Svelte code.
