### ISSUE TITLE
API design lacks any notion of error handling

### ISSUE THREAD

**Issue by apriori** [burn-rs/burn#803]
Hello everyone, 

I tried e.g. candle from huggingface and am now trying to work with this framework. What really puzzles me, is that virtually the entire API designs lacks any kind of exposure of `Result` types. Why is that the case? In general it is a bad idea to rely on panicking for all possible errors, especially if you want to build any kind of reliable system. Why was this approach taken?

**Comment by antimora** [comment]
In response to your question regarding the use of `Result` types in Burn's API design:

To provide a general context, not all APIs within Burn handle errors the same way. Specific cases must be analyzed individually. The crux of Burn primarily involves mathematical computations. When these mathematical operations are performed, the calls are generally designed to succeed unless they encounter unrecoverable edge cases or failed assumptions, which are ensured by assert statements. When such rare occurrences happen, the objective is to let the system fault, prompting the implementer to correct any issues to ensure the accuracy of the provided data. Given the infrequent nature of these cases in relation to the total calls made, it was decided not to use each operation with result returns. This decision was made keeping in mind the overhead it might cause for developers ensuring correct call implementations. For those wanting a safeguard against application crashes during model's forward method calls, Rust's [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) can be employed.

For instances involving I/O, such as the [sqlite dataset](https://github.com/burn-rs/burn/blob/main/burn-dataset/src/dataset/sqlite.rs), we indeed use the `Result` type to allow users to manage errors effectively, offering the flexibility to retry or pursue alternative solutions.

Moreover, in the burn-import crate designed for ONNX import, you'll notice an extensive use of asserts leading to potential panics. This approach was adopted due to a couple of reasons: the crate is still under active development with evolving APIs, and the intent is to detect and address any issues upfront should an underlying assumption fail. Furthermore, the primary API call at present is through the `build.rs` script, so there is no other use case requiring result.

I'd like to emphasize that this explanation is not meant to justify every design decision made. There may indeed be instances where the API could be improved. Feedback and suggestions are always welcome, and the team is continually striving to enhance the API for the better.

**Comment by nathanielsimard** [comment]
Hi @apriori, the choice to use `panic!` is explicit and with good reasons backed by the recommendations from the Rust Book: https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html

The main point is that errors from tensor operations can't be recovered from; those are _programming errors_, not _runtime errors_, with the only exception of out-of-memory errors. But even the Rust standard library doesn't return results on allocations, since it would pollute every codebase with too many irrelevant errors.

When you face an error from a tensor operation, you normally have to change your code, recompile everything, and try again! We try to provide the best error messages so that your development process is as easy as possible.

This strategy doesn't impact robustness; maybe returning a result adds an illusion of robustness, but at the end of the day, if there is nothing you can do with it except to unwrap, it's not really helpful. By not returning a Result, we ensure that the community won't pollute their models with unwrap, making modeling code less readable.

**Comment by antimora** [comment]
Closing this as resolve. If you have more follow up questions, you can add more comments or re-open it.
