### ISSUE TITLE
Length look up for sqlite dataset is slow for very large databases

### ISSUE THREAD

**Issue by jggc** [burn-rs/burn#811]
### Feature description
Pretty simple : I have a 918GB sqlite dataset that takes over 30 minutes from a Sata SSD to `select count(*) from <table>` in sqlite.rs#250.

### Feature motivation
Speeeed

### (Optional) Suggest a Solution
 ```sql
CREATE UNIQUE INDEX train_row_id_index on train (row_id);
```
 when creating the sqlite database.

Hopepfully I have time soon to open a p-r for this but it's sadly unlikely...

**Comment by antimora** [comment]
row_id is already indexed because it's a primary key. See the table creation: https://github.com/burn-rs/burn/blob/main/burn-dataset/src/dataset/sqlite.rs#L580

Can you try this?

```sql
SELECT COUNT(row_id) FROM table;
```

if this helps, we can change the length function to use this select statement here: https://github.com/burn-rs/burn/blob/main/burn-dataset/src/dataset/sqlite.rs#L250

**Comment by antimora** [comment]
Alternatively this could work if no data was deleted (which is true for Dataset db):

https://stackoverflow.com/a/17109826/29122

```sql
SELECT MAX(ROWID) FROM "table" LIMIT 1;
```

This will avoid full table scan and it uses table's psedo/built-in column: `ROWID`.

**Comment by antimora** [comment]
Another super fast option: https://sqlite-users.sqlite.narkive.com/cuhhKQr4/sqlite-sqlite3-performance-on-select-count-very-slow-for-16-gb-file#post3

```sql
select seq from sqlite_sequence where name = 'tablename'
```

**Comment by jggc** [comment]
Maybe `SELECT COUNT(row_id)` would work, I'll try after my training (6 days to go).

The other two options rely on the fact that nothing has been deleted, which is IMO too weak to be acceptable.

**Comment by antimora** [comment]
You can also use sqlite command utility to open the database while training and try running the SQL statement. It won't affect your training. Or you can copy if you have enough space. It would easier if you could confirm. Otherwise I have to find big enough db or create it by script.

**Comment by jggc** [comment]
I know I can open the DB but I'd rather not drop and rebuild the big index during training, it would slow things down a bit.

I tried with my validation table and I can confirm that `SELECT COUNT(row_id) FROM table;` is SLOW without an index. On my validation table I have 360k elements and it takes about 1 second without the index and it is instantaneous with the index.

I tried about 10 times to make sure any fs caching did not impact the speed.

**Comment by antimora** [comment]
Thanks for verifying and reporting it. I will fix it and confirm myself if the solution works.

**Comment by antimora** [comment]
It is odd that look up fast on the primary key but select count(row_id) is slow but fast with a separate index. Probably unique index is stored separately and behaves differently than pk index.

**Comment by antimora** [comment]
OK. I have settled on a solution and submitted a PR. Here is my reasoning:

Instead of using select count(*) from split, we are replacing with select coalesce(max(row_id), 0) from which is instantaneous for very large databases (tested for 260GB db).

The coalesce(max(row_id), 0) returns 0 if the table is empty, otherwise it returns the max row_id, which corresponds to the number of rows in the table. The main assumption, which always holds true, is that the row_id is always increasing and there are no gaps. This is true for all the datasets that we are using, otherwise row_id will not correspond to the index (+1). row_id must not have gaps. If someone remove rows manually, they should update the row_ids as well.

We are not using unique index for row_id because it slows down insertion considerably (post creation is also very slow) and it is unnecessary for the dataset usage with always true assumptions about row_id ( row_id will always correspond to index (+1). )

**Comment by antimora** [comment]
@jggc, it would be great if you could confirm this change helped your case. Your data remains untouched. We only changed the way how the data is selected.
