### ISSUE TITLE
[Question] Why don't tensors implement the Copy trait?

### ISSUE THREAD

**Issue by EddieMataEwy** [burn-rs/burn#932]
Hi, I was just wondering why tensors implement the `Clone` trait but not the `Copy` trait.
What is the reason for this?

I just find myself writing `.clone()` over and over again, and I don't see any reason why you couldn't derive `Copy` as well.

Thank you for your time.

**Comment by EddieMataEwy** [comment]
I see. In retrospect that was a dumb question. I just saw the Tensors are implemented as Arc Arrays.
In this case, would it be possible to have many of the tensor ops take a reference to a tensor so that the compiler implements dereference coercion automatically? Or would we run into similar issues?

**Comment by nathanielsimard** [comment]
Most of the optimizations of Burn are because we use owned tensors as arguments for all our operations. Using the ownership system to know when a tensor can be reused. This allows us to capture the graph and is fundamental in our optimization strategy with the upcoming burn-fusion. So, using tensor as reference would actually make this impossible and slow down the framework. I agree that calling clone when reusing a tensor isn't really pretty, but you can actually use clippy to minimize the number of clones and, in the same way, optimize your model!

**Comment by EddieMataEwy** [comment]
Gotcha! Thanks for the explanation and for your time. Your work here is amazing. Keep going!
